module.exports={
	PAGE_ACCESS_TOKEN:`EAAVJaTNZCZAGsBAHm2yzG6vAfhXwm80FXhbZBbciQOPupmMMQ0tpDqpQamUIXDHZAJ0gpUu6fTixPsGqKEprPJYiTXfDaWZB1QZA7Xg35atRjpzF9uCfqGXVnLgCthrxHKoK1ZCBRZAZBZAmgNnMyZAiYXZBBG7uKzt320InnVsptFnYhgZDZD`,
	VERIFY_TOKEN:`lospecessonamigosnocomida`,
	MONGO_URL:'mongodb://localhost:27017/lenna'
}